# This Dockerfile is used to build an image containing the python
# app gromari, a grow room management tool.

FROM ubuntu:rolling
MAINTAINER Randy Olive <randy.jr.olive@gmail.com>

# Add apt-cacher proxy
RUN echo 'Acquire::http::Proxy "http://10.0.1.210:3142";' | tee /etc/apt/apt.conf.d/01proxy

# Install apt-utils
RUN apt-get update \
    && apt-get install apt-utils -y

# Make sure the package repository is up to date.
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y dist-upgrade

# Install packages needed for running the app
RUN apt-get update && apt-get install -y \
    libcairo2-dev \
    libxml2-dev \
    nano \
    postgresql-client \
    python3 \
    python3-pip \
    supervisor

# Set the working directory inside the container
RUN mkdir /code
WORKDIR /code
ADD . /code

# Use pip3 to install python dependencies from requirements.txt
RUN pip3 install -r requirements.txt --no-cache-dir

# Clean up apt after installations
RUN apt-get autoremove --purge -y \
    && apt-get autoclean \
    && apt-get clean \
    && echo "removing apt lists" \
    && rm -rf /var/lib/apt/lists/* \
    && echo "removing apt cache" \
    && rm -rf /var/cache/apt/archives/*

# setup directories and log files for supervisor
ADD ./config/supervisor/gromari_celery.conf /etc/supervisor/conf.d/
ADD ./config/supervisor/gromari_celerybeat.conf /etc/supervisor/conf.d/
RUN mkdir -p /code/log/celery/
RUN touch /code/log/celery/gromari_worker.log
RUN touch /code/log/celery/gromari_beat.log

RUN mkdir -p /code/log/gromari/
RUN touch /code/log/gromari/gromari.log
