# This Dockerfile is used to build an image containing nginx using a custom
# config file

FROM nginx:latest
MAINTAINER Randy Olive <randy.jr.olive@gmail.com>

ADD ./config/nginx/gromari.conf /etc/nginx/conf.d/
