# This Dockerfile is used to build an image containing the python
# app gromari, a grow room management tool.

FROM ubuntu:rolling
MAINTAINER Randy Olive <randy.jr.olive@gmail.com>

# Install apt-utils
RUN apt-get update \
    && apt-get install apt-utils -y

# Install packages needed for running the app
RUN apt-get update && apt-get install -y \
    firefox \
    libcairo2-dev \
    libxml2-dev \
    nano \
    postgresql-client \
    python3 \
    python3-pip \
    supervisor

# Set the working directory inside the container
RUN mkdir /code
WORKDIR /code

# Use pip3 to install python dependencies from requirements.txt
ADD requirements.txt /code
RUN pip3 install -r requirements.txt

# add project code to the container
ADD . /code

# Clean up apt after installations
RUN apt-get autoremove --purge -y \
    && apt-get autoclean \
    && apt-get clean \
    && echo "removing apt lists" \
    && rm -rf /var/lib/apt/lists/* \
    && echo "removing apt cache" \
    && rm -rf /var/cache/apt/archives/*

# setup directories and log files for supervisor & celery
ADD ./config/supervisor/gromari_celery.conf /etc/supervisor/conf.d/
ADD ./config/supervisor/gromari_celerybeat.conf /etc/supervisor/conf.d/
RUN mkdir -p /code/log/celery/
RUN touch /code/log/celery/gromari_worker.log
RUN touch /code/log/celery/gromari_beat.log
RUN mkdir -p /code/log/gromari/
RUN touch /code/log/gromari/gromari.log

# moves the geckodriver to /usr/local/bin for use with selenium tests
RUN mv /code/geckodriver/geckodriver /usr/local/bin/geckodriver
